HERITAGE-348/enrichment_aggs
nationalarchives/ds-ohos-wagtail pull request #119
Opened 2024-08-07 10:35 UTC by JohnHeeryTNA

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-348

## About these changes

I have adapted the js to use the enrichment_aggs variable

## How to check these changes

Run branch locally, check functionality

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [x] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

2024-08-08 13:12 UTC, TNA-Allan requested changes

2024-08-13 10:31 UTC, JohnHeeryTNA commented on scripts/src/modules/tag-frequency/data/aggregations.js
The api is now being used instead of the static data

2024-08-13 10:31 UTC, JohnHeeryTNA commented on scripts/src/modules/tag-frequency/process-aggregation-data.js
> +import { enrichment_aggs } from "./data/aggregations.js";
api data is now being used

2024-08-13 10:32 UTC, JohnHeeryTNA commented on scripts/src/modules/tag-frequency/process-aggregation-data.js
>          JSON.parse(chartContainer.getAttribute("data-js-tag-frequency-data")) ??
The adjustments to the form have now been made

2024-08-13 11:01 UTC, TNA-Allan approved these changes
Thanks @JohnHeeryTNA

2024-08-13 11:01 UTC, merged