HERITAGE-72 Update results list card template to meet OHOS requirements
nationalarchives/ds-ohos-wagtail pull request #26
Opened 2023-11-28 11:58 UTC by garethmead

Ticket URL: [HERITAGE-72](https://national-archives.atlassian.net/browse/HERITAGE-72)

## About these changes

Update search results cards to match OHOS requirements. Hard coded elements included with comments until API data is available

## How to check these changes

Search results can be found at - `/search/catalogue/?group=digitised`

## Before assigning to reviewer, please make sure you have

- [x] Checked things thoroughly before handing over to reviewer
- [x] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [x] Ensured that PR includes only commits relevant to the ticket
- [x] Waited for all CI jobs to pass before requesting a review
- [ ] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

[HERITAGE-72]: https://national-archives.atlassian.net/browse/HERITAGE-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-11-28 12:04 UTC, garethmead commented
The icon used differs slightly from the one in the design, as the font-awesome style used for that has been removed from tna-frontend here - https://github.com/nationalarchives/tna-frontend/commit/d512254b49c2bab3fb7c25609e0a44920a9d436e. As the style isn’t used anywhere else it would be a bit of overhead for the sake of a single icon

2023-11-28 14:21 UTC, TNA-Allan requested changes
I've put a comment in the ticket
Re: 
> I’d recommend not to remove, 

> Icons for ‘Held by’, ‘Date’ and ‘Reference’

> Rows for ‘Held by’ and ‘Reference’

> as this belongs to TNA (2nd) or NON TNA (3rd) buckets. It will not show for DCC (1st bucket) when we integrate the data for DCC.

> but will show for TNA and NON TNA

2023-11-28 14:54 UTC, TNA-Allan commented
> Leave this as is as Digitised is not in the scope as per the Wireframe. It will be removed by HERITAGE-92: Remove unrequired ETNA code - IN PROGRESS The bucket itself will not show.
> 
> (updated)

Hi @garethmead 
As per latest comments, it needs to be removed from TNA as well. So retain removal of condition with `record.is_digitised` 
Thanks :)

2023-11-28 16:29 UTC, garethmead commented
> > Leave this as is as Digitised is not in the scope as per the Wireframe. It will be removed by HERITAGE-92: Remove unrequired ETNA code - IN PROGRESS The bucket itself will not show.
> > (updated)
> 
> Hi @garethmead As per latest comments, it needs to be removed from TNA as well. So retain removal of condition with `record.is_digitised` Thanks :)

I've reinstated the additional fields but kept them commented out. With regard to the icons, as they're not in the design I've kept them removed, as we'd also need to find an icon for `Collection`

2023-11-29 09:33 UTC, ahosgood approved these changes

2023-11-29 10:39 UTC, TNA-Allan requested changes

2023-11-29 10:39 UTC, TNA-Allan commented on templates/search/blocks/search_results__list-card--grid.html
> -            {% endif %}
same, please reinstate this as commented inside new dl, for the purpose of tna,non-tna buckets

2023-11-29 10:39 UTC, TNA-Allan commented on templates/search/blocks/search_results__list-card--grid.html
> -                </dt>
same, please reinstate this as commented inside new dl, for the purpose of tna,non-tna buckets

2023-11-29 10:39 UTC, TNA-Allan commented on templates/search/blocks/search_results__list-card--grid.html
> -            {% comment %}End debug attributes.{% endcomment %}
same, please reinstate this as commented inside new dl, for the purpose of tna,non-tna buckets

2023-11-29 10:39 UTC, TNA-Allan commented on templates/search/blocks/search_results__list-card.html
> -                <i class="fa-solid fa-landmark"></i>
same, please reinstate this as commented inside new dl, for the purpose of tna,non-tna buckets

2023-11-29 10:39 UTC, TNA-Allan commented on templates/search/blocks/search_results__list-card.html
> -                <i class="fa-solid fa-calendar"></i>
same, please reinstate this as commented inside new dl, for the purpose of tna,non-tna buckets

2023-11-29 10:39 UTC, TNA-Allan commented on templates/search/blocks/search_results__list-card.html
> -                <i class="fa-solid fa-database"></i>
same, please reinstate this as commented inside new dl, for the purpose of tna,non-tna buckets

2023-11-29 10:41 UTC, TNA-Allan commented
> > > Leave this as is as Digitised is not in the scope as per the Wireframe. It will be removed by HERITAGE-92: Remove unrequired ETNA code - IN PROGRESS The bucket itself will not show.
> > > (updated)
> > 
> > 
> > Hi @garethmead As per latest comments, it needs to be removed from TNA as well. So retain removal of condition with `record.is_digitised` Thanks :)
> 
> I've reinstated the additional fields but kept them commented out. With regard to the icons, as they're not in the design I've kept them removed, as we'd also need to find an icon for `Collection`

Thanks @garethmead , with regard to the etna icons, I've suggested to reinstate as commented as you've done with others. When we have TNA,NON-TNA data, will take a look and uncomment accordingly.

2023-11-29 11:49 UTC, garethmead commented
@TNA-Allan Icons added back in with the commented fields. For simplicity I've kept all of these within the same `dl` and we can figure out what needs to stay/be removed once the data is integrated

2023-11-29 14:20 UTC, TNA-Allan approved these changes
Investigated and noted this ticket succeeds HERITAGE-89 Remove grid and list options from sort by area on Search Results
Looks good. Thanks @garethmead

2023-11-29 14:20 UTC, merged