HERITAGE-89 Remove option to select list and grid view on results page
nationalarchives/ds-ohos-wagtail pull request #29
Opened 2023-11-28 15:20 UTC by garethmead

Ticket URL: [HERITAGE-89](https://national-archives.atlassian.net/browse/HERITAGE-89)

## About these changes

Removed user controls to display results in list or grid view. As a result of this I've also removed the templates and logic within the template to display a grid view as this is now surplus to requirements

## How to check these changes

Controls removed to the right of the Sort by on `/search/catalogue/`

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [ ] Ensured that PR includes only commits relevant to the ticket
- [ ] Waited for all CI jobs to pass before requesting a review
- [ ] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

2023-11-28 16:30 UTC, TNA-Allan requested changes
May need changes, as discussed in the ticket.

2023-11-28 16:35 UTC, TNA-Allan approved these changes
> May need changes, as discussed in the ticket.

My bad, its for all buckets. Approving

2023-11-29 09:33 UTC, ahosgood approved these changes

2023-11-29 10:21 UTC, merged

2023-11-29 14:16 UTC, TNA-Allan reviewed
Investigated and noted this ticket succeeds HERITAGE-89 Remove grid and list options from sort by area on Search Results
Looks good. Thanks @garethmead