HERITAGE-326 Add styles for no results messaging
nationalarchives/ds-ohos-wagtail pull request #98
Opened 2024-06-07 13:13 UTC by garethmead

Ticket URL: [HERITAGE-326](https://national-archives.atlassian.net/browse/HERITAGE-326)

## About these changes

Add styling for new "No results" messaging

## How to check these changes

Ticket linked provides 3 different scenarios for showing no results

## Before assigning to reviewer, please make sure you have

- [ ] Checked things thoroughly before handing over to reviewer
- [ ] Checked PR title starts with ticket number as per project conventions to help us keep track of changes
- [ ] Ensured that PR includes only commits relevant to the ticket
- [ ] Waited for all CI jobs to pass before requesting a review
- [ ] Added/updated tests and documentation where relevant

## Merging PR guidance

Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contributing/)

## Deployment guidance

Follow [docs\infra\environments.md](https://nationalarchives.github.io/ds-wagtail/infra/environments/)

2024-06-07 14:20 UTC, TNA-Allan requested changes

2024-06-07 14:20 UTC, TNA-Allan commented on templates/search/blocks/no_results.html
> +            <li>Use fewer keyword</li>
```suggestion
            <li>Use fewer keywords</li>
```

2024-06-07 14:28 UTC, TNA-Allan approved these changes
Thanks @garethmead Looks good from BE perspective. Will wait for a FE approval.

2024-06-11 09:56 UTC, ahosgood approved these changes

2024-06-11 11:24 UTC, merged